const doctorsData = [
    {
        id: 3001,
        name: "Dr.Aasha Sarath",
        shortDegree: "M.D, PH.D",
        treatField: "Sexual Counselling, Stress and Worry",
        experience: 16,
        edu1: "National Specialist Register in Mantal Health",
        edu2: "Mental Care Department of Science Major",
        award1: "Industry Innovator Award",
        award2: "Prescription of Medicine",
        award3: "CMA Honorary Membership Award",
        award4: "Best Doctor for Women",
        award5: "Pregnancy Care for Women 2016",
        img: "https://ibb.co/pd8YKRs"
    },

    {
        id: 3002,
        name: "Dr.Arafath",
        shortDegree: "M.D, PH.D",
        treatField: "Relationship Problems, Sexual Counselling",
        experience: 18,
        edu1: "National Specialist Register in Mantal Health",
        edu2: "Mental Care Department of Science Major",
        award1: "Industry Innovator Award",
        award2: "Prescription of Medicine",
        award3: "CMA Honorary Membership Award",
        award4: "Best Doctor for Women",
        award5: "Pregnancy Care for Women 2016",
        img: "https://ibb.co/yf8Y6Vz"
    },
    {
        id: 3003,
        name: "Dr.Steve Finn",
        shortDegree: "M.D, FCPS",
        treatField: "Children Problems, Psychosocial Counselling",
        experience: 20,
        edu1: "National Specialist Register in Mantal Health",
        edu2: "Mental Care Department of Science Major",
        award1: "Industry Innovator Award",
        award2: "Prescription of Medicine",
        award3: "CMA Honorary Membership Award",
        award4: "Best Doctor for Women",
        award5: "Pregnancy Care for Women 2016",
        img: "https://ibb.co/vZZWrMT"
    },
    {
        id: 3004,
        name: "Dr.Nicolas Hondu",
        shortDegree: "M.D, D.T.S",
        treatField: "Depression treatment, Family difficulties",
        experience: 12,
        edu1: "National Specialist Register in Mantal Health",
        edu2: "Mental Care Department of Science Major",
        award1: "Industry Innovator Award",
        award2: "Prescription of Medicine",
        award3: "CMA Honorary Membership Award",
        award4: "Best Doctor for Women",
        award5: "Pregnancy Care for Women 2016",
        img: "https://ibb.co/c3XPNpq"
    },
]